### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by scentiic** [DominikHolzapfel/Fundgrube-Finder#1]
Hi, 

weiß gar nicht, ob das hier noch aktuell ist, aber ich erhalte immer einen Traceback Fehler, mir fehlt allerdings die Expertise dafür um das zu lösen. 

Searching MediaMarkt Köln City am Dom
Traceback (most recent call last):
  File "E:\Downloads\finder.py", line 68, in <module>
    search_store(brand, store)
  File "E:\Downloads\finder.py", line 39, in search_store
    j = json.loads(r.text[9:-2])    # assumes &callback= is missing, which leads to callback=callback
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 9 (char 8)

**Comment by DominikHolzapfel** [comment]
Hallo,

in der Tat wurden die Fundgruben von Mediamarkt und Saturn inzwischen deutlich überarbeitet, inklusive besserer (wenn auch noch nicht perfekter) Filtermöglichkeiten.
Wenn ich in nächster Zeit mal dazu komme, mir das ganze anzusehen, stelle ich eventuell ein Update ein. Ich kann aber nichts versprechen.
